name: NikolayBezhko
favicon: null
layout_spectrum: 0.7769647005479783
typography_spectrum: 0.11002729763276875
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9092588142957538
  lightness: 0.97580446745269
  saturation: 0.14951461902819574
  rhythmicContrast: 0.4214543991256505
purpose: []
