name: NikolayBezhko
favicon: null
layout_spectrum: 0.73945
typography_spectrum: 0.76949
title: Nikolay Bezhko
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70419709-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#324d24'
    - '#ebd842'
    - '#9fa771'
    - '#687844'
  brandStrength: 0.75
  lightness: 0.97580446745269
  saturation: 0.14951461902819574
  rhythmicContrast: 0.4214543991256505
purpose: []
